### ISSUE TITLE
docker部署问题

### ISSUE THREAD

**Issue by debugAllTheTime** [Sneezry/Azure-ChatGPT-Next-Web#2]
请问一下如果纯使用Azure openai。请问怎么部署呢？（实在抱歉我有点不太会编程，还在学习当中）

**Comment by Sneezry** [comment]
如果只想用 Azure OpenAI 的接口可以用我 fork 的 repo：https://github.com/Sneezry/ChatGPT-Next-Web

这里的 readme 里环境变量怎么设置写的比较清楚，你照着 docker 的步骤把 Azure 相关的环境变量指定好就可以了。

**Comment by debugAllTheTime** [comment]
相当于是使用repo：https://github.com/Sneezry/ChatGPT-Next-Web，然后在docker run的时候
-e AZURE_API_KEY=“xxxx”
-e AZURE_ACCOUNT=“xxxx”
-e AZURE_MODEL=“xxxx”
将这三个作为docker run的参数嘛？

**Comment by Sneezry** [comment]
对的，但需要注意就像那个 repo readme 里说的，用 Azure 就不要设置 `OPENAI_API_KEY` 了

**Comment by debugAllTheTime** [comment]
好的。感谢！

**Comment by debugAllTheTime** [comment]
我先去fork一下然后推送一下docker

**Comment by debugAllTheTime** [comment]
你好我这边一直报错
![image](https://user-images.githubusercontent.com/25170510/233826293-0d3ffb56-1177-4020-a012-ce148cd7edce.png)

我的docker启动的指令是
```
docker run \
   -d -p 14091:3000 \
   -e AZURE_API_KEY=“XXXXX” \
   -e AZURE_ACCOUNT=“XXXXX” \
   -e AZURE_MODEL=“gpt-35-turbo” \
   -e CODE="0000" \
   naokuoyoudiantong/azure-openai-chatgpt-next-web
```
您看这个有问题吗？这个镜像是fork你的repo：https://github.com/Sneezry/ChatGPT-Next-Web后推送到dockerhub的

**Comment by Sneezry** [comment]
`gpt-35-turbo` 是你的 Azure OpenAI deployment name，是不是和你实际的不一致？

**Comment by debugAllTheTime** [comment]
是一致的欸？难道是chat0305uestc
![image](https://user-images.githubusercontent.com/25170510/233827972-54202d10-085d-4d96-ae28-e95e94fa6978.png)

**Comment by Sneezry** [comment]
的确是一致的，那你的 env 设置的没问题。你看看 docker log 里有什么错误信息呢？

**Comment by debugAllTheTime** [comment]
好像是类型转换的问题？
具体报错信息如下：
```
Error [TypeError]: Cannot convert argument to a ByteString because the character atindex 0 has a value of 8220 which is greater than 255.
    at webidl.converters.ByteString (evalmachine.<anonymous>:1500:17)
    at Headers3.set (evalmachine.<anonymous>:1825:35)
    at Object.middleware [as handler] (file:///app/.next/server/middleware.js:1206:25)
```

全部的log信息如下：
```
Listening on port 3000 url: http://66df63e68436:3000
[Auth] allowed hashed codes:  []
[Auth] got access code:
[Auth] hashed access code: d41d8cd98f00b204e9800998ecf8427e
[Auth] set system azure token
Error [TypeError]: Cannot convert argument to a ByteString because the character atindex 0 has a value of 8220 which is greater than 255.
    at webidl.converters.ByteString (evalmachine.<anonymous>:1500:17)
    at Headers3.set (evalmachine.<anonymous>:1825:35)
    at Object.middleware [as handler] (file:///app/.next/server/middleware.js:1206:25)
    at adapter (file:///app/.next/server/middleware.js:976:33)
    at next_middleware_loaderabsolutePagePath_private_next_root_dir_2Fmiddleware_ts_page_2Fmiddleware_rootDir_2Fapp_matchers_W3sicmVnZXhwIjoiXig_2FOlxcLyhfbmV4dFxcL2RhdGFcXC9bXi9dezEsfSkpP1xcL2FwaVxcL29wZW5haSguanNvbik_2FW1xcLyNcXD9dPyQiLCJvcmlnaW5hbFNvdXJjZSI6Ii86bmV4dERhdGEoX25leHQvZGF0YS9bXi9dezEsfSk_2FL2FwaS9vcGVuYWkoLmpzb24pPyJ9LHsicmVnZXhwIjoiXig_2FOlxcLyhfbmV4dFxcL2RhdGFcXC9bXi9dezEsfSkpP1xcL2FwaVxcL2NoYXQtc3RyZWFtKC5qc29uKT9bXFwvI1xcP10_2FJCIsIm9yaWdpbmFsU291cmNlIjoiLzpuZXh0RGF0YShfbmV4dC9kYXRhL1teL117MSx9KT8vYXBpL2NoYXQtc3RyZWFtKC5qc29uKT8ifV0_3D_ (file:///app/.next/server/middleware.js:1125:18)
    at <unknown> (file:///app/node_modules/next/dist/server/web/sandbox/sandbox.js:74:30)
    at async NextNodeServer.runMiddleware (file:///app/node_modules/next/dist/server/next-server.js:1177:24)
    at async Object.fn (file:///app/node_modules/next/dist/server/next-server.js:1256:38)
    at async Router.execute (file:///app/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (file:///app/node_modules/next/dist/server/base-server.js:432:29)
```

**Comment by Sneezry** [comment]
可能是你命令里引号的问题导致的。

![image](https://user-images.githubusercontent.com/1621293/233828718-93ab179c-f7c8-48cb-8f4f-310943a17c64.png)

**Comment by debugAllTheTime** [comment]
oh~~~~~是这样的。我没看到是中文引号！非常感谢！已经可以使用了
